### PR TITLE
secp_wrapper - pre-publication

### PR DESCRIPTION
**Pull request by D4nte**
Mostly aesthetics changes and documentation.

Once this PR is merged, I will create `coblox/chosen-name`, push the code in, publish it in crates.io and make a PR to use the published crate and remove it from comit-rs so approve with care :)

Work towards #1255.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
> Once this PR is merged, I will create coblox/chosen-name, push the code in, publish it in crates.io and make a PR to use the published crate and remove it from comit-rs so approve with care :)

So we don't get a chance to iterate on this? I have a couple of ideas :)

**Comment by D4nte** [comment]
> > Once this PR is merged, I will create coblox/chosen-name, push the code in, publish it in crates.io and make a PR to use the published crate and remove it from comit-rs so approve with care :)
> 
> So we don't get a chance to iterate on this? I have a couple of ideas :)

Hum, I did say "approve with care" :)

If you want to do a follow-up PR I am happy to get this one in and wait for you.

**Comment by thomaseizinger** [comment]
> If you want to do a follow-up PR I am happy to get this one in and wait for you.

Also happy to just discuss the ideas / write them into issues to make them more visible :)

**Comment by D4nte** [comment]
Discussed with @thomaseizinger.

The aim to "clean-up the secp_support crate" is to easily get blockchain-contracts in a new repo. Why? Because:
- we only modify blockchain_contracts when we do blockchain scripting (rare)
- It comes with a bunch of docker/blockchain nodes test that takes time
- If we want to try HTLC on a new blockchain, we would need to change blockchain-contracts first, today it would mean compiling comit-rs for that

Hence, I am going to try go get blockchain-contracts out instead.

**Pull request closed without merging**
