### PR TITLE
Only talk to the blockchain nodes if really necessary

### PR DESCRIPTION
**Pull request by thomaseizinger**
Instead of pre-maturely fetching the current time from the blockchain
connectors, we pass the future along and only await it if we run
into a refund scenario and need to compare it to the expiry time.

This should significantly speed up calls to GET /swap in any other
case.

### CODE REVIEW

**Review by D4nte — APPROVED** [review]
I think this is good enough for now but I believe we'll have to optimise further to not have the hanging in a refund scenario.

- Could we cache the current time based on the block we received last?
- Could we check the system time first and only if we are "close enough" to the expiry then check blockchain time?

**Comment by thomaseizinger** [comment]
> I think this is good enough for now but I believe we'll have to optimise further to not have the hanging in a refund scenario.
> 
>     * Could we cache the current time based on the block we received last?
> 
>     * Could we check the system time first and only if we are "close enough" to the expiry then check blockchain time?

Excellent ideas!
I was looking into caching it based on the last block but wasn't quite sure how and where I should be introducing an abstraction.

The 2nd idea is also good, we can keep that in mind in the future :)

**Comment by D4nte** [comment]
> Excellent ideas!
> I was looking into caching it based on the last block but wasn't quite sure how and where I should be introducing an abstraction.
> 
> The 2nd idea is also good, we can keep that in mind in the future :)

**Comment by D4nte** [comment]
> Excellent ideas!
Thanks 😬
> I was looking into caching it based on the last block but wasn't quite sure how and where I should be introducing an abstraction.

I don't think this idea holds if we move from block processing to filters anyway.

**Review by da-kami — APPROVED** [review]

**Review by tcharding — COMMENTED** [review]
Nice idea!

**Pull request merged**
