### PR TITLE
Use task to format all modified files regardless of their staging

### PR DESCRIPTION
**Pull request by D4nte**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
IMO, this creates to much noise in our Makefile. I'd rather have the original task changed instead of creating all this duplication. We should settle on one workflow.

Looking at only modified files instead of staged ones seems fine to me.

**Comment by da-kami** [comment]
bors retry

**Comment by thomaseizinger** [comment]
> bors retry

Instead of hammering our CI, we could also just wait until the proposed fix is in ...

cc https://github.com/comit-network/comit-rs/pull/1881

**Comment by D4nte** [comment]
> > bors retry
> 
> @da-kami Instead of hammering our CI, we could also just wait until the proposed fix is in ...
> 
> cc #1881

I am pretty sure it did not make the relation between both (neither did I)
🔨🔨🔨

**Comment by thomaseizinger** [comment]
> > > bors retry
> > 
> > 
> > @da-kami Instead of hammering our CI, we could also just wait until the proposed fix is in ...
> > cc #1881
> 
> I am pretty sure it did not make the relation between both (neither did I)
> hammerhammerhammer

Maybe I should have been more explicit in my status update on basecamp. I mentioned that our e2e tests are broken and my 1st priority on Monday is to fix them. That is what the other PR is doing.

**Comment by thomaseizinger** [comment]
@D4nte fixed the merge conflicts for you :)

**Comment by D4nte** [comment]
@thomaseizinger strange, it's marked as failed but I thought your PR to fix e2e was merged? Do I need to hammer? 🔨

**Pull request merged**
