### PR TITLE
Improve version printing for cnd

### LINKED ISSUE #1417: Improve version printing
## Problem

As a comit-rs dev, I sometimes install a compiled version of comit-rs with `cargo install -p .` to have quick easy access to `cnd`.

However, once it is installed, it is not possible to differentiate two non-tagged versions of `cnd`: all binaries show the version from the `Cargo.toml` file of master.

## Goal

Make `cnd` return its git commit hash in addition of the Cargo.toml version

## Recommendation

Include the git hash as part of the version:
- `--version` prints out version + commit hash and exit
- AND print version + commit hash as first line of logs when starting

Inspire yourself from:
- https://stackoverflow.com/questions/43753491/include-git-commit-hash-as-string-into-rust-program#44407625
- https://docs.rs/vergen/3.0.4/vergen/
- https://github.com/TeXitoi/structopt/issues/136#issuecomment-429119703

### PR DESCRIPTION
**Pull request by karen**
Fixes #1417.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@D4nte I am gonna assign you to this as you wrote the initial issue :)

**Comment by D4nte** [comment]
Hi @karen, thank you for the contribution!

I would like to still have the version of cnd from the Cargo manifest, can you please add it?

**Comment by D4nte** [comment]
Also, please run `cargo tomlfmt` and `cargo fmt` to format everything properly for the CI.

**Comment by D4nte** [comment]
@karen you also need to sign the CLA please otherwise we can merge the PR :(

**Comment by karen** [comment]
Hi @D4nte, sorry about the delay. I don't think I can sign it without permission from my employer so I'm waiting on that.

**Comment by D4nte** [comment]
@karen please let us know whether you are able to sign the CLA or I will close this stale issue on the 11Nov.

**Comment by karen** [comment]
Hi @D4nte, thanks for your understanding. Unfortunately I haven't got permission yet. Please feel free to close it if that would be more convenient.

**Comment by thomaseizinger** [comment]
Hi @karen,

do you have a rough ETA by when you would be able to get that approval? I'd hate to leave to contributions unmerged just because of that :(
I will close the PRs for now to reduce the noise on our board. Feel free to re-open them at any time once things are sorted out.

Thanks for your understanding!

**Comment by karen** [comment]
@thomaseizinger I've put in a request but am not sure of the ETA unfortunately. Sure, I will do that once I've got the approval.

**Pull request closed without merging**
