### PR TITLE
New command to migrate the database to a new format

### PR DESCRIPTION
**Pull request by D4nte**
Use `nectar migrate-db status` to check if migration is needed;
If so, backup your data and then execute `nectar migrate-db run` to
proceed with the migration.

### CODE REVIEW

**Comment by da-kami** [comment]
Tried to run it in production, `./nectar migrate-db status` works:

```
Database migration is needed due to nectar format upgrade. Backup your database located at '"/home/dakami/.local/share/nectar/database"' first.
```

However, `./nectar migrate-db run gave me an error:

```
thread 'main' panicked at 'import is overwriting existing data', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:381:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Backtrace:

```
thread 'main' panicked at 'import is overwriting existing data', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:381:25
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
   1: sled::db::Db::import
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:381
   2: nectar::database::Database::reimport
             at /home/runner/work/comit-rs/comit-rs/nectar/src/database.rs:240
   3: nectar::command::migrate_db::run::{{closure}}
             at /home/runner/work/comit-rs/comit-rs/nectar/src/command/migrate_db.rs:58
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
   5: nectar::command::migrate_db::migrate_db::{{closure}}
             at /home/runner/work/comit-rs/comit-rs/nectar/src/command/migrate_db.rs:23
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
   7: nectar::main::{{closure}}
             at /home/runner/work/comit-rs/comit-rs/nectar/src/main.rs:206
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
   9: tokio::runtime::enter::Enter::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  10: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265
  12: std::thread::local::LocalKey<T>::with
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241
  13: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  14: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  15: tokio::runtime::enter::Enter::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  16: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/mod.rs:82
  17: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:446
  18: tokio::runtime::context::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  19: tokio::runtime::handle::Handle::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  20: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  21: nectar::main
             at /home/runner/work/comit-rs/comit-rs/nectar/src/main.rs:67
  22: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by D4nte** [comment]
ah :( Thanks @da-kami!

**Comment by D4nte** [comment]
> Tried to run it in production, `./nectar migrate-db status` works:
> 
> ```
> Database migration is needed due to nectar format upgrade. Backup your database located at '"/home/dakami/.local/share/nectar/database"' first.
> ```
> 
> However, `./nectar migrate-db run gave me an error:
> 
> ```
> thread 'main' panicked at 'import is overwriting existing data', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:381:25
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Backtrace:
> 
> ```
> thread 'main' panicked at 'import is overwriting existing data', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:381:25
> stack backtrace:
>    0: std::panicking::begin_panic
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
>    1: sled::db::Db::import
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:381
>    2: nectar::database::Database::reimport
>              at /home/runner/work/comit-rs/comit-rs/nectar/src/database.rs:240
>    3: nectar::command::migrate_db::run::{{closure}}
>              at /home/runner/work/comit-rs/comit-rs/nectar/src/command/migrate_db.rs:58
>    4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
>    5: nectar::command::migrate_db::migrate_db::{{closure}}
>              at /home/runner/work/comit-rs/comit-rs/nectar/src/command/migrate_db.rs:23
>    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
>    7: nectar::main::{{closure}}
>              at /home/runner/work/comit-rs/comit-rs/nectar/src/main.rs:206
>    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79
>    9: tokio::runtime::enter::Enter::block_on::{{closure}}
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
>   10: tokio::coop::with_budget::{{closure}}
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
>   11: std::thread::local::LocalKey<T>::try_with
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265
>   12: std::thread::local::LocalKey<T>::with
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241
>   13: tokio::coop::with_budget
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
>   14: tokio::coop::budget
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
>   15: tokio::runtime::enter::Enter::block_on
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
>   16: tokio::runtime::thread_pool::ThreadPool::block_on
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/mod.rs:82
>   17: tokio::runtime::Runtime::block_on::{{closure}}
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:446
>   18: tokio::runtime::context::enter
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
>   19: tokio::runtime::handle::Handle::enter
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
>   20: tokio::runtime::Runtime::block_on
>              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
>   21: nectar::main
>              at /home/runner/work/comit-rs/comit-rs/nectar/src/main.rs:67
>   22: core::ops::function::FnOnce::call_once
>              at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

Should be fixed now @da-kami

**Comment by da-kami** [comment]
It seems that the previous version already did run the command (or caused the database to be reset when restarting nectar). Unfortunately cannot test this atm, because I get:

```
dakami@bitcoind:~/nectar_run$ ./nectar migrate-db run
Using config file at default path: /home/dakami/.config/nectar/config.toml
2020-11-02T00:17:02.851007Z  INFO nectar::trace: Initialized tracing with level: DEBUG
2020-11-02T00:17:02.851100Z  INFO nectar: Initializing sentry with URL https://724f3dbcd9f34c50bb774d7228ab6146@o461938.ingest.sentry.io/5464474
2020-11-02T00:17:02.857691Z  INFO nectar::config::seed: Read in seed from file: /home/dakami/.local/share/nectar/seed.pem
Error: Database migration is not necessary
```

**Review by da-kami — APPROVED** [review]
Even though I could not test it any more, let's bring it in. In case there is still a bug I'd report it once we run into it.

**Comment by D4nte** [comment]
> It seems that the previous version already did run the command (or caused the database to be reset when restarting nectar). Unfortunately cannot test this atm, because I get:
> 
> ```
> dakami@bitcoind:~/nectar_run$ ./nectar migrate-db run
> Using config file at default path: /home/dakami/.config/nectar/config.toml
> 2020-11-02T00:17:02.851007Z  INFO nectar::trace: Initialized tracing with level: DEBUG
> 2020-11-02T00:17:02.851100Z  INFO nectar: Initializing sentry with URL https://724f3dbcd9f34c50bb774d7228ab6146@o461938.ingest.sentry.io/5464474
> 2020-11-02T00:17:02.857691Z  INFO nectar::config::seed: Read in seed from file: /home/dakami/.local/share/nectar/seed.pem
> Error: Database migration is not necessary
> ```

You only need a migration if you have swaps in the db.
As we delete the swaps in the db once execution is finished then it could explain why you don't have the issue anymore.

**Comment by D4nte** [comment]
Let's get it in as it does not hurt and could help.

In the future, I would recommend migration to sqlite as per https://lists.comit.network/pipermail/comit-dev/2020-November/000018.html

**Review by thomaseizinger — APPROVED** [review]

**Pull request merged**
