### PR TITLE
Few fixes to migrations.sh

### PR DESCRIPTION
**Pull request by tcharding**
A few fixes to the `migrations.sh` script. The first minor the second fundamental, please review carefully to check I'm not missing something. 

- Patch one fixes the fact that the script does not run on Linux using `./migrations.sh`

- Patch two fixes the fact that the script does not get the current version correctly, it currently returns v0.7.3 and we are on v0.8.0

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Interesting, we seem to be doing something wrong with our release branch merging. `git describe` _should_ work!

**Comment by thomaseizinger** [comment]
I think a problem with your approach could be that it doesn't take into account the current HEAD. It just gives you the latest release regardless of where you are in tree.

**Comment by tcharding** [comment]
> I think a problem with your approach could be that it doesn't take into account the current HEAD. It just gives you the latest release regardless of where you are in tree.

Oh, you are right. Easy fix; we could add a check and warn if running the script on a branch other than dev?

E.g.
"You are not on dev, if there is a tagged commit in dev that is not in this branch script output will be incorrect"

**Comment by thomaseizinger** [comment]
Do you mind looking into why `git describe` doesn't cut it?

**Comment by tcharding** [comment]
> Do you mind looking into why `git describe` doesn't cut it?

Sure thing, can do.

**Pull request merged**
