### PR TITLE
Remove some noise from the e2e test declarations

### PR DESCRIPTION
**Pull request by thomaseizinger**
We have several layers of function calls here that can be reduced.
Unfortunately, it does not reduce the indentation yet but I think
this is a step in the right direction. Anyway, we can remove a layer
of indirection that is unnecessary.

### CODE REVIEW

**Comment by D4nte** [comment]
Are you saying it's a step in the right direction because we are decrease functions calls in favour of returning functions themselves?

**Comment by thomaseizinger** [comment]
> Are you saying it's a step in the right direction because we are decreasing functions calls in favour of returning functions themselves?

Yes basically. Overall, anything that decreases noise in tests is usually good :)

**Comment by D4nte** [comment]
> > Are you saying it's a step in the right direction because we are decreasing functions calls in favour of returning functions themselves?
> 
> Yes basically. Overall, anything that decreases noise in tests is usually good :)

How does it decreases noise?

**Comment by thomaseizinger** [comment]
> > > Are you saying it's a step in the right direction because we are decreasing functions calls in favour of returning functions themselves?
> > 
> > 
> > Yes basically. Overall, anything that decreases noise in tests is usually good :)
> 
> How does it decrease noise?

The patch removes one instance of the `await`, `async` and `function` keyword per test.

**Pull request merged**
