### PR TITLE
Remove as much of the old swaps API as we currently can

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by D4nte — APPROVED** [review]

**Comment by D4nte** [comment]
Bold move.

**Comment by thomaseizinger** [comment]
> Bold move.

Is it? Would you prefer we keep the API and re-implement it using `setup-swap` on the network layer?

**Comment by D4nte** [comment]
> > Bold move.
> 
> Is it? Would you prefer we keep the API and re-implement it using `setup-swap` on the network layer?

I think it's bold but in a good way ;)

**Review by tcharding — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Obsolete with #3336.

**Pull request closed without merging**
