### PR TITLE
Add `identity` module

### PR DESCRIPTION
**Pull request by tcharding**
Our domain is cross chain.  We should have domain specific terms for
things in various chains.  We currently have the `asset` module and the
`ledger` module that do just this.

Add and `identity` module that defines an identity/address on a chain.
With this applied we can write

```
	let address = identity::Ethereum::new(...)
```
Instead of
```
	let address = ethereum::Address::new(...)
```
which is actually just a re-export of:
```
	let address = web3::types::Address::new(...)
```

Similarly we have `identity::Bitcoin` for the Bitcoin addresses.

### CODE REVIEW

**Comment by tcharding** [comment]
Check this out!  I had this idea while trying to raise the Identity (Ledger associated type) up in preparation for removing it.  This makes adding all the concrete types to the db layer way less taxing to write and read because one can just glance and see the `Bitcoin`/`Ethereum` stuff for ledgers, assets, and now identities match instead of having to mentally map `PublicKey` to a Bitcoin identity.

**Comment by tcharding** [comment]
If this is approved we can then also add `src/cnd/transaction.rs` in a similar fashion so that we can write `transaction::Bitcoin` instead of `bitcoin::Transaction`.  This at first seems like no benefit but I would argue that we should be cross-chain first i.e., we are primarily concerned with transactions _not_ with Bitcoin so we should sort on what we are primarily concerned with instead of sorting by the underlying thing.

**Comment by thomaseizinger** [comment]
> If this is approved we can then also add `src/cnd/transaction.rs` in a similar fashion so that we can write `transaction::Bitcoin` instead of `bitcoin::Transaction`. This at first seems like no benefit but I would argue that we should be cross-chain first i.e., we are primarily concerned with transactions _not_ with Bitcoin so we should sort on what we are primarily concerned with instead of sorting by the underlying thing.

That is a good observation! I like it :)

The only thing to consider is that **if** we ever want to provide compile-time feature-flags for the support of certain ledgers, we have to put them in several places.
I don't see us doing that in the near future so it shouldn't matter!

**Comment by tcharding** [comment]
Added the `transaction` module and put them both in `lib.rs`.  Adding `no-mergify` label to give reviewers (@thomaseizinger, and @D4nte) a chance to look at it again.  Perhaps one of you could remove the label if you think its ok to merge this, one new extra opinion should be enough?

**Comment by thomaseizinger** [comment]
ACK from my side but I would like the modules to be used as-well. Otherwise it is just dead code :/

**Comment by tcharding** [comment]
> ACK from my side but I would like the modules to be used as-well. Otherwise it is just dead code :/

Will do, thanks.

**Comment by D4nte** [comment]
Still looks good to me. I would not mind several follow-up PRs to sort it out.

**Comment by tcharding** [comment]
Removed the transaction module (since it adds dead code).  Squashed commits while I was at it since force push is required anyways.  This now just adds the `identity` module, and uses it in a few places.  It will be heavily used in the 'remove Ledger trait' work.

**Pull request merged**
