### PR TITLE
Move modules to directories

### PR DESCRIPTION
**Pull request by tcharding**
We have `cnd/src/foo.rs` and `cnd/src/foo`.  The rest of our modules use
a `mod.rs` file for this structure.  Uniformity hastens development.

- Move `cnd/src/btsieve.rs` -> `cnd/src/btsieve/mod.rs`
- Move `cnd/src/ethereum.rs` -> `cnd/src/ethereum/mod.rs`

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Happy to make it uniform now. What are your thoughts of changing it into the other direction though eventually?

I think the main rationale of the Rust people with the Rust 2018 edition change was that it is pointless having 17 `mod.rs` files open in your editor. Should eventually migrate to the other format?

cc @luckysori because he is also using emacs (I assume this affects emacs people more than CLion as CLion has a tree-structure as part of the IDE, whereas emacs people navigate by filename very often).

**Comment by tcharding** [comment]
> Happy to make it uniform now. What are your thoughts of changing it into the other direction though eventually?

I have no preference, as long as its uniform.  We should do whatever the rest of the Rust community is doing and you are better positioned to know this @thomaseizinger.

> I think the main rationale of the Rust people with the Rust 2018 edition change was that it is pointless having 17 `mod.rs` files open in your editor. Should eventually migrate to the other format?

I'm totally use to hitting the first character of the enclosing directory to differentiate but I can very much see myself liking it the other way if it means less key strokes. 

> cc @luckysori because he is also using emacs (I assume this affects emacs people more than CLion as CLion has a tree-structure as part of the IDE, whereas emacs people navigate by filename very often).

**Comment by thomaseizinger** [comment]
> > Happy to make it uniform now. What are your thoughts of changing it into the other direction though eventually?
> 
> I have no preference, as long as its uniform. We should do whatever the rest of the Rust community is doing and you are better positioned to know this @thomaseizinger.
> 
> > I think the main rationale of the Rust people with the Rust 2018 edition change was that it is pointless having 17 `mod.rs` files open in your editor. Should eventually migrate to the other format?
> 
> I'm totally use to hitting the first character of the enclosing directory to differentiate but I can very much see myself liking it the other way if it means less key strokes.
> 
> > cc @luckysori because he is also using emacs (I assume this affects emacs people more than CLion as CLion has a tree-structure as part of the IDE, whereas emacs people navigate by filename very often).

I will take that as a vote for using the Rust 2018 style. Thoughts @luckysori ?

**Comment by tcharding** [comment]
Closing this.  The patch is in https://github.com/comit-network/comit-rs/pull/1735 anyways and consensus is, if I understand everyone correctly, its fine to do this now to be uniform and we can change it all later.

**Comment by luckysori** [comment]
> > > Happy to make it uniform now. What are your thoughts of changing it into the other direction though eventually?
> > 
> > 
> > I have no preference, as long as its uniform. We should do whatever the rest of the Rust community is doing and you are better positioned to know this @thomaseizinger.
> > > I think the main rationale of the Rust people with the Rust 2018 edition change was that it is pointless having 17 `mod.rs` files open in your editor. Should eventually migrate to the other format?
> > 
> > 
> > I'm totally use to hitting the first character of the enclosing directory to differentiate but I can very much see myself liking it the other way if it means less key strokes.
> > > cc @luckysori because he is also using emacs (I assume this affects emacs people more than CLion as CLion has a tree-structure as part of the IDE, whereas emacs people navigate by filename very often).
> 
> I will take that as a vote for using the Rust 2018 style. Thoughts @luckysori ?

I don't mind either. I'm happy to go with the Rust 2018 style.

**Pull request closed without merging**
