### PR TITLE
Fix formatting error

### PR DESCRIPTION
**Pull request by bonomat**
Not sure how we could miss this, but I fixed it!
Bug was in rustfmt.toml

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Is this an April fool joke?

**Comment by bonomat** [comment]
> Coming back from the dead to block this 4eva

Your forgot to run `cargo make format` 🤪

**Comment by bonomat** [comment]
Closed for now. Will need to rediscuss this in a year or so 😬

**Comment by D4nte** [comment]
hahahaha

**Pull request closed without merging**
