### PR TITLE
Also assign when ready for review

### PR DESCRIPTION
**Pull request by D4nte**
To have Draft PR auto assigned.

### CODE REVIEW

**Comment by D4nte** [comment]
So this worked as soon as I opened the PR. I am confused. I'll open a new draft PR on comit-rs soon and see what it does.

**Comment by D4nte** [comment]
@tcharding I have now changed the base branch to dev.

**Comment by thomaseizinger** [comment]
@D4nte is this still relevant or can we close it?

**Comment by D4nte** [comment]
Confirmed with https://github.com/comit-network/comit-rs/pull/2052 that it is actually not an issue.

**Pull request closed without merging**
